name: RepoSense - Proyectos Taller

on:
  workflow_dispatch:      # Para ejecutarlo a mano
  push:
    branches: [ "main" ]  # Cambi√° a "master" si tu rama principal se llama master

jobs:
  reposense:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (dummy, requerido por Actions)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run RepoSense para todos los repos
        uses: reposense/reposense-action@v1
        with:
          repos: |
            https://github.com/miguelciotta013/proyecto_02.git
            https://github.com/Gime26/FinalTika.git
            https://github.com/maxiguaymas/GestionEmpleados-NE.git
            https://github.com/JULFABOR/PUERTO_REAL.git
            https://github.com/IgnacioCasula/LaMercedComestiblesSuper.git
            https://github.com/Ezze-F/MiTiendaMateo.git
            https://github.com/JorgeRQuiroga/AtleticGYM.git
          output_dir: ./reposense-report
          since: "2024-01-01"
          formats: "html"
